/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CreateImport } from './routes/create'
import { Route as CompaniesImport } from './routes/companies'
import { Route as layoutImport } from './routes/__layout'
import { Route as IndexImport } from './routes/index'
import { Route as CompaniesIndexImport } from './routes/companies.index'
import { Route as IndexStatsImport } from './routes/index.stats'
import { Route as IndexCustomersImport } from './routes/index.customers'
import { Route as CompaniesIdImport } from './routes/companies.$id'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const CreateRoute = CreateImport.update({
  path: '/create',
  getParentRoute: () => rootRoute,
} as any)

const CompaniesRoute = CompaniesImport.update({
  path: '/companies',
  getParentRoute: () => rootRoute,
} as any)

const layoutRoute = layoutImport.update({
  id: '/__layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CompaniesIndexRoute = CompaniesIndexImport.update({
  path: '/',
  getParentRoute: () => CompaniesRoute,
} as any)

const IndexStatsRoute = IndexStatsImport.update({
  path: '/index/stats',
  getParentRoute: () => rootRoute,
} as any)

const IndexCustomersRoute = IndexCustomersImport.update({
  path: '/index/customers',
  getParentRoute: () => rootRoute,
} as any)

const CompaniesIdRoute = CompaniesIdImport.update({
  path: '/$id',
  getParentRoute: () => CompaniesRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/__layout': {
      id: '/__layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof layoutImport
      parentRoute: typeof rootRoute
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesImport
      parentRoute: typeof rootRoute
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/companies/$id': {
      id: '/companies/$id'
      path: '/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof CompaniesIdImport
      parentRoute: typeof CompaniesImport
    }
    '/index/customers': {
      id: '/index/customers'
      path: '/index/customers'
      fullPath: '/index/customers'
      preLoaderRoute: typeof IndexCustomersImport
      parentRoute: typeof rootRoute
    }
    '/index/stats': {
      id: '/index/stats'
      path: '/index/stats'
      fullPath: '/index/stats'
      preLoaderRoute: typeof IndexStatsImport
      parentRoute: typeof rootRoute
    }
    '/companies/': {
      id: '/companies/'
      path: '/'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexImport
      parentRoute: typeof CompaniesImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  CompaniesRoute: CompaniesRoute.addChildren({
    CompaniesIdRoute,
    CompaniesIndexRoute,
  }),
  CreateRoute,
  AboutLazyRoute,
  IndexCustomersRoute,
  IndexStatsRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/__layout",
        "/companies",
        "/create",
        "/about",
        "/index/customers",
        "/index/stats"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/__layout": {
      "filePath": "__layout.tsx"
    },
    "/companies": {
      "filePath": "companies.tsx",
      "children": [
        "/companies/$id",
        "/companies/"
      ]
    },
    "/create": {
      "filePath": "create.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/companies/$id": {
      "filePath": "companies.$id.tsx",
      "parent": "/companies"
    },
    "/index/customers": {
      "filePath": "index.customers.tsx"
    },
    "/index/stats": {
      "filePath": "index.stats.tsx"
    },
    "/companies/": {
      "filePath": "companies.index.tsx",
      "parent": "/companies"
    }
  }
}
ROUTE_MANIFEST_END */
